version: 0.2
env:
  variables:
    BUCKET:
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET  --output-template-file packaged-template.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - packaged-template.yaml