AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-ses

  SAM Template for lambda-ses

Globals:
  Function:
    Timeout: 3
Parameters:
  EMAIL:
    Type: String
    Description: SES verified e-mail address to send and receive
Resources:
  LambdaSESFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: lambda-ses
      CodeUri: lambda-ses/
      Handler: app.handler
      Runtime: nodejs12.x
      Policies:
        - AWSXRayDaemonWriteAccess
        - Statement:
            - Sid: SendEmails
              Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: '*'
      Environment:
        Variables:
          EMAIL: !Ref EMAIL
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce


Outputs:
  LambdaSESFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt LambdaSESFunction.Arn
  LambdaSESFunctionIamRole:
    Description: "Implicit IAM Role created for lambda-ses function"
    Value: !GetAtt LambdaSESFunctionRole.Arn
