AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-ses

  SAM Template for lambda-ses

Globals:
  Function:
    Timeout: 3
Parameters:
  EMAIL:
    Type: String
    Description: SES verified e-mail address to send and receive
Resources:
  LambdaSESFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda-ses/
      Handler: app.handler
      Runtime: nodejs12.x
      Policies:
        - Statement:
            - Sid: SendEmails
              Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: '*'

      Environment:
        Variables:
          EMAIL: !Ref EMAIL
#      Events:
#        LambdaSES:
#          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
#          Properties:
#            Path: /contact
#            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  #  LambdaSESFunctionApi:
  #    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
  #    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/contact/"
  LambdaSESFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt LambdaSESFunction.Arn
  LambdaSESFunctionIamRole:
    Description: "Implicit IAM Role created for lambda-ses function"
    Value: !GetAtt LambdaSESFunctionRole.Arn
